info:
  app:
    name: @project.name@
    description: @project.description@
    groupId:  @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: @project.artifactId@
  profiles:
    active: default
  cloud:
    config:
      enabled: true
      profile: v01
      label: master
      fail-fast: true

server:
  servlet.contextPath: /ckan-conector-ws
