info:
  app:
    name: @project.name@
    description: @project.description@
    groupId:  @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@

spring:
  application:
    name: @project.artifactId@

server:
  servlet.contextPath: /ckan-conector-ws
